### ISSUE TITLE
"Blog title" is interpreted as a company

### ISSUE THREAD

**Issue by dandv** [fabienwang/Ghost-Flat#1]
The `Blog title` setting from General is interpreted as a sort of company, and displays a Copyright message in the footer:

![image](https://cloud.githubusercontent.com/assets/33569/7556092/3d254080-f731-11e4-82a0-baf9d05894aa.png)

I've filed an issue with Ghost because this affects multiple themes.

**Comment by fabienwang** [comment]
Hello @dandv.
Thanks for the report. I was also intrigued by how Ghost missed the possibility to create variables with static values in the Admin panel. They recently added Code Injection part but it's to add quickly some scripts in your pages, like Piwik or Google Analytics tracker codes, or adverts etc...
So far, the only way I could express a copyright owner would either Blog Title or the Author of First post.
As mentioned in the [#5251](https://github.com/TryGhost/Ghost/issues/5251) on Ghost, it's quite easy for a person to go change the partials/footer.hbs and customize it.

**Comment by fabienwang** [comment]
As a blog can be for a company or organisation, it's better to use Blog Title than first author name. I will now close this issue as it has been closed in Ghost too.
