### ISSUE TITLE
Sorry to raise this as an issue but...

### ISSUE THREAD

**Issue by xcellardoor** [fabienwang/Ghost-Flat#10]
Hi,

Not really an issue but I couldn't find any other way to contact you...

How do I change the default banner across the top in posts? I can change it on the homepage using Ghost's built in functionality, but for posts which haven't got a 'header banner' or whatever you'd like to call it defined... It defaults to some flowery graphic. In your example it's got a cool brown graphic.

Could you tell me how to change it please? Many thanks.

**Comment by fabienwang** [comment]
Hello, this is called "post cover image" and was added in Ghost in september 2014… :)
Here it is: https://blog.ghost.org/post-cover-images/

I hope it's what you wanted.

**Comment by xcellardoor** [comment]
Yes this does thank you! I was hoping there was a way to do it automatically for all posts but this is better. Many thanks!
