### ISSUE TITLE
Change date

### ISSUE THREAD

**Issue by itielshwartz** [fabienwang/Ghost-Flat#3]
Hi,

is there a way to change the posts dates on main page to refresh automatically, and not just when writing a new post?

thanks,
BTW great theme.

**Comment by fabienwang** [comment]
Thanks @itielshwartz 
There is a related issue on Ghost repository: https://github.com/TryGhost/Ghost/issues/2487

I guess you could overwrite it or just wait.

**Comment by fabienwang** [comment]
@fabienwang So i closed the issue !
