### ISSUE TITLE
Light blue text on ruby red background

### ISSUE THREAD

**Issue by younishd** [fabienwang/Ghost-Flat#9]
![](https://raw.githubusercontent.com/fabienwang/Ghost-Flat/master/ghost-flat-main.png)

My eyes have ebola now.

**Comment by Schoewilliam** [comment]
+1

**Comment by fabienwang** [comment]
The cover image is part of my data and has nothing to do with the theme.
People can still change colors in the css or choose a nice cover unlike me xD
